import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { execSync } from 'node:child_process';
const here=path.dirname(url.fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const absent=(p)=>!fs.existsSync(path.join(root,p));
const app=read('src/App.tsx');
const css=read('src/index.css');
const settings=read('src/components/SettingsModal.tsx');
const store=read('src/store.ts');
const desk=read('src/components/DeskPhone.tsx');
const dtmf=read('src/lib/dtmf.ts');
const bridge=read('src/lib/bridge.ts');
const mock=read('scripts/mock-phone-bridge.mjs');
const html=read('index.html');
const pkg=JSON.parse(read('package.json'));
const lock=JSON.parse(read('package-lock.json'));
let passed=0;
const results=[];
function check(name, ok){ if(!ok) throw new Error(`FAIL: ${name}`); passed++; results.push(`PASS ${String(passed).padStart(2,'0')} ${name}`); }
function has(text,needle){return text.includes(needle);}
function not(text,needle){return !text.includes(needle);}
check('Build version is 0.16.0', pkg.version==='0.16.0' && lock.version==='0.16.0' && lock.packages[''].version==='0.16.0');
check('Package is the desk phone, not the CRM', pkg.name==='deskphone' && pkg.scripts['mock-bridge']==='node scripts/mock-phone-bridge.mjs');
check('Fixed wide mobile viewport is present', /width=1200/.test(html) && /user-scalable=yes/.test(html));
check('Inter font is loaded', /family=Inter/.test(html));
check('Page title is Desk Phone', has(html,'<title>Desk Phone</title>'));
check('Inter is the global font token', has(css,"--font-family-main: 'Inter'"));
check('Controls inherit Inter globally', has(css,'button, input, textarea, select, option, a {\n  font-family: var(--font-family-main);\n}'));
check('Tailwind is not a project dependency', !pkg.dependencies?.tailwindcss && !pkg.devDependencies?.tailwindcss && !pkg.dependencies?.['@tailwindcss/vite'] && !pkg.devDependencies?.['@tailwindcss/vite']);
check('Authoritative CSS is a single file without Tailwind import', not(css,'@import "tailwindcss"') && not(css,'@apply ') && not(css,'@tailwind '));
check('Vite has no Tailwind plugin', not(read('vite.config.ts'),'tailwindcss') && not(read('vite.config.ts'),'tailwind'));
check('React source has no Tailwind utility overlays', !/\b(font-sans|text-slate-|bg-slate-|bg-white\/|fixed inset-0|md:left-8|backdrop-blur|divide-x|grid-cols-4)\b/.test(app+desk+settings));
check('Canvas uses dashboard page color', has(css,'--bg-canvas: #F2F4F8;') && has(store,"canvasColor: '#F2F4F8'"));
check('Topbar is thin at 52px', has(css,'--topbar-h: 52px;'));
check('Rounded panel token is 9px', has(css,'--radius-panel: 9px;'));
check('Dashboard surface tokens are present', has(css,'--bg-surface: #FFFFFF;') && has(css,'--bg-panel: #F7F8FC;') && has(css,'--accent-navy: #1E2235;'));
check('Accepted accents are blue teal amber navy', has(css,'--accent-blue: #3B6FD4;') && has(css,'--accent-teal: #1A8F7A;') && has(css,'--accent-amber: #C97B2A;') && has(css,'--accent-navy: #1E2235;'));
check('Navigation defaults to dashboard navy', has(store,"sidebarColor: '#1E2235'"));
check('Accent light tints are implemented', has(css,'--accent-teal-light: #E5F6F3;') && has(css,'--accent-blue-light: #EAF0FF;'));
check('Communication rows use accepted accent tints', has(css,'.comm-type-icon.call') && has(css,'.comm-type-icon.email') && has(desk,'comm-type-icon sms') && has(desk,'comm-type-icon call'));
check('Icons stand alone without tile backgrounds', not(css,'.comm-type-icon.sms { background'));
check('Search fields use the dashboard focus ring', has(css,'.comm-search:focus-within') && has(css,'0 0 0 3px var(--accent-blue-light)'));
check('Neon purple and neon green are absent', !/#25C47A|#6B4EBC/i.test(css+app+desk));
check('Authoritative CSS has no !important', !css.includes('!important'));
check('The running app is a full-window desk phone', has(app,'DeskPhone') && has(css,'.desk-app') && has(css,'.desk-shell') && has(css,'.desk-dialer'));
check('CRM leads rail is not mounted', not(app,'LeadsRail') && not(app,'LeadDetailPanel') && not(app,'NavRail') && not(store,'leads:'));
check('Phone chrome is not an iPhone bezel', not(css,'.iphone-bezel') && not(css,'.iphone-island') && not(css,'.iphone-home-bar') && not(desk,'iphone-bezel') && not(app,'IPhoneFrame'));
check('Messages Recents Contacts and Mail are in the rail', has(desk,"tab=\"messages\"") && has(desk,"tab=\"recents\"") && has(desk,"tab=\"contacts\"") && has(desk,"tab=\"mail\""));
check('Dialer stays on the right', has(desk,'desk-dialer') && has(desk,'DialPad') && has(css,'grid-template-columns: 92px minmax(0, 1fr) 300px'));
check('Font size uses plus/minus controls', has(settings,'<Minus size={16}/>') && has(settings,'<Plus size={16}/>'));
check('Font changes in 0.5px steps', has(settings,'changeFont(-0.5)') && has(settings,'changeFont(0.5)'));
check('Canvas colors are configurable', has(settings,'CANVAS_COLORS') && has(store,"canvasColor: '#F2F4F8'"));
check('Top bar color is configurable', has(settings,'NAV_COLORS') && has(store,'sidebarColor'));
check('Settings persist locally', has(store,'localStorage.setItem(SETTINGS_KEY'));
check('Default left pane is configurable', has(settings,'Default left pane') && has(store,'defaultCommsTab'));
check('Windows bridge token can be pasted in Settings', has(settings,'Windows bridge token') && has(settings,'bridge-token.txt') && has(bridge,'BRIDGE_TOKEN_KEY'));
check('Message conversation rows are clickable', has(desk,'setThreadKey(thread.key)'));
check('Call rows place a call', has(desk,'void startCall(item.number)'));
check('Contact rows are clickable', has(desk,'setOpenContact(item)'));
check('Contacts have a search field', has(desk,'placeholder="Search contacts"'));
check('Contacts are grouped alphabetically', has(desk,'groupedContacts'));
check('Contact call icon is available', has(desk,'title="Call"'));
check('Contact SMS icon is available', has(desk,'title="SMS"'));
check('Contact WhatsApp icon is available', has(desk,'title="WhatsApp"'));
check('Contact email icon is available', has(desk,'title="Email"'));
check('Message bubbles keep corner timestamps and double-check receipts', has(desk,'comm-bubble-meta') && has(desk,'<CheckCheck size={12}') && has(css,'.comm-bubble-wrap {') && has(css,'.comm-bubble-meta {'));
check('Bubble layout lives in CSS, not inline style patches', not(desk,'style={{') && not(app,'style={{'));
check('Message composer is inline', has(desk,'className="comm-composer"'));
check('Message Send uses paper-plane icon', has(desk,'<Send size={15}/>'));
check('Email compose/reply is inline', has(desk,'className="comm-email-compose"'));
check('Email Subject is inline', has(desk,'className="comm-email-subject"') && has(desk,'placeholder="Subject"'));
check('Multiple contact emails can be selected', has(desk,'openContact.emails.map'));
check('No video icon exists in communications', not(desk,'Video'));
check('Native dial pad uses DTMF tones', has(dtmf,'playDtmf') && has(dtmf,'697, 1209') && has(desk,'playDtmf'));
check('Computer keyboard digits drive the dial pad', has(desk,"key === '*'") && has(desk,'Backspace') && has(desk,"key === 'Enter'") && has(desk,'appendDial'));
check('Enter places a call from the dial pad', has(desk,'startCall') && has(desk,"key === 'Enter'"));
check('Enter sends an SMS from the composer', has(desk,'sendMessage') && has(desk,"e.key === 'Enter' && !e.shiftKey"));
check('Multiple Bluetooth phones can be selected', has(desk,'link-device-row') && has(bridge,'selectedDeviceId') && has(desk,'setSelectedDeviceId'));
check('Extracted lists are filtered to the selected phone', has(bridge,'item.deviceId === selectedDeviceId'));
check('Bridge auto-extracts when a connected phone set changes', has(bridge,'connectedKey') && has(bridge,'/refresh-inbox') && has(bridge,'setInterval'));
check('Mock bridge can skip the token', has(bridge,'authRequired !== false') && has(mock,'authRequired: false'));
check('Mock bridge presents two connected phones', has(mock,"Name: 'iPhone'") && has(mock,"Name: 'Pixel 8'") && has(mock,'connectedPhones'));
check('Hang up is attempted over HTTP and explained when missing', has(desk,'hangUp') && has(bridge,"'/hangup'") && has(desk,'Hang up on the phone'));
check('iMessage FaceTime and voicemail are not invented', not(desk,'iMessage') && not(desk,'FaceTime') && not(desk,'Voicemail') && not(app,'iMessage') && not(mock,'iMessage'));
check('No Twilio or call vendor SDK is bundled', !/twilio|voice-sdk|softphone|sip\.js|webrtc-adapter/i.test(JSON.stringify({ ...pkg.dependencies, ...pkg.devDependencies })));
check('Twilio backend modules are deleted from disk', absent('src/components/TopbarDialer.tsx') && absent('src/components/CallDock.tsx') && absent('src/lib/telephony.ts'));
check('No call-token backend or script remains', absent('api') && absent('server') && not(JSON.stringify(pkg.scripts),'token-server'));
check('Call action never navigates the app to tel:', not(app,'window.location.href') && not(app,'tel:') && not(desk,'tel:'));
check('Call action supports ForgeTelephonyAdapter', has(desk,'ForgeTelephonyAdapter'));
check('Call action supports the Windows Bluetooth bridge', has(desk,'bridge.placeCall') && has(bridge,"'/call'"));
check('Call action supports Electron/mobile event handoff', has(desk,"new CustomEvent('forge:call-request'"));
check('Unhandled call request shows a notice', has(desk,'Connect a Bluetooth phone through the Windows bridge to place calls.'));
check('Mock banner is honest', has(desk,'Local mock with two connected phones') && has(desk,'does not invent Apple messaging'));
check('Mail is honest mailto', has(desk,'mailto:') && has(desk,'There is no mailbox sync in this build'));
check('No form tags exist that can accidentally submit/reload', !/<form\b/i.test(app+desk+settings));
check('All explicit action buttons use type=button', (app+desk+settings).includes('type="button"'));
check('Panel scrollbars are hidden until hover', has(css,'scrollbar-color: transparent transparent') && has(css,'::-webkit-scrollbar-thumb:hover'));
check('Scrollbar width is skinny', has(css,'width: 4px;') && has(css,'height: 4px;'));
check('Ultra-wide scaling media query is present', has(css,'@media (min-width: 1920px)') && has(css,'--topbar-h: 60px;'));
check('Unused autoprefixer and esbuild deps are gone', !pkg.devDependencies?.autoprefixer && !pkg.dependencies?.esbuild && !pkg.devDependencies?.esbuild);
check('Lockfile has no Tailwind packages', !JSON.stringify(lock).includes('tailwindcss') && !JSON.stringify(lock).includes('@tailwindcss'));
const zipList = execSync('unzip -l downloads/DeskPhone-016.zip', { encoding: 'utf8' });
check('Download zip uses the DeskPhone-016 name', zipList.includes('DeskPhone-016/package-lock.json') && zipList.includes('DeskPhone-016/package.json') && zipList.includes('DeskPhone-016/src/index.css') && zipList.includes('DeskPhone-016/src/components/DeskPhone.tsx') && zipList.includes('DeskPhone-016/src/lib/dtmf.ts') && zipList.includes('DeskPhone-016/src/lib/bridge.ts') && zipList.includes('DeskPhone-016/scripts/mock-phone-bridge.mjs') && zipList.includes('DeskPhone-016/vite.config.ts'));
check('Old CRM zip names are gone', absent('downloads/Forge-CRM-016.zip') && absent('downloads/DeskPhoneCRM-016.zip') && !zipList.includes('Forge-CRM-016/') && !zipList.includes('DeskPhoneCRM-016/'));
check('Download zip has no leftover docs tests or dumps', !zipList.includes('README.md') && !zipList.includes('source-audit') && !zipList.includes('pack-downloads') && !zipList.includes('SOURCE.txt') && !zipList.includes('.gitignore'));
check('Download zip has no Tailwind leftover configs', !zipList.includes('tailwind.config') && !zipList.includes('postcss.config'));
check('Download zip has no CRM panels', !zipList.includes('LeadDetailPanel') && !zipList.includes('LeadsRail') && !zipList.includes('data.ts'));
console.log(results.join('\n'));
console.log(`TOTAL ${passed}/${passed} PASS`);
