import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
const here=path.dirname(url.fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const app=read('src/App.tsx');
const css=read('src/index.css');
const nav=read('src/components/NavRail.tsx');
const settings=read('src/components/SettingsModal.tsx');
const store=read('src/store.ts');
const comm=read('src/components/IOSCommPanel.tsx');
const leads=read('src/components/LeadsRail.tsx');
const detail=read('src/components/LeadDetailPanel.tsx');
const messages=read('src/components/MessagesView.tsx');
const statement=read('src/components/StatementDocument.tsx');
const viewer=read('src/components/StatementViewerOverlay.tsx');
const data=read('src/data.ts');
const format=read('src/lib/format.ts');
const html=read('index.html');
const pkg=JSON.parse(read('package.json'));
const lock=JSON.parse(read('package-lock.json'));
let passed=0;
const results=[];
function check(name, ok){ if(!ok) throw new Error(`FAIL: ${name}`); passed++; results.push(`PASS ${String(passed).padStart(2,'0')} ${name}`); }
function has(text,needle){return text.includes(needle);}
function not(text,needle){return !text.includes(needle);}
check('Build version is 0.16.0', pkg.version==='0.16.0' && lock.version==='0.16.0' && lock.packages[''].version==='0.16.0');
check('Fixed wide mobile viewport is present', /width=1200/.test(html) && /user-scalable=yes/.test(html));
check('Inter font is loaded', /family=Inter/.test(html));
check('Inter is the global font token', has(css,"--font-family-main: 'Inter'"));
check('Controls inherit Inter globally', has(css,'button, input, textarea, select, option, a {\n  font-family: var(--font-family-main);\n}'));
check('Statement viewer uses sans/Inter instead of mono', has(statement,'font-sans') && not(statement,'font-mono'));
check('Canvas uses dashboard page color', has(css,'--bg-canvas: #F2F4F8;') && has(store,"canvasColor: '#F2F4F8'"));
check('Topbar is thin at 52px', has(css,'--topbar-h: 52px;'));
check('Traffic dots center in slim sidebar', has(css,'.forge-sidebar.slim .forge-sidebar-head') && has(css,'padding: 6px 0;'));
check('Rounded panel token is 9px', has(css,'--radius-panel: 9px;'));
check('Dashboard surface tokens are present', has(css,'--bg-surface: #FFFFFF;') && has(css,'--bg-panel: #F7F8FC;') && has(css,'--accent-navy: #1E2235;'));
check('Accepted accents are blue teal amber navy', has(css,'--accent-blue: #3B6FD4;') && has(css,'--accent-teal: #1A8F7A;') && has(css,'--accent-amber: #C97B2A;') && has(css,'--accent-navy: #1E2235;'));
check('Navigation defaults to dashboard navy', has(store,"sidebarColor: '#1E2235'"));
check('Accent light tints are implemented', has(css,'--accent-teal-light: #E5F6F3;') && has(css,'--accent-amber-light: #FDF3E5;') && has(css,'--accent-blue-light: #EAF0FF;'));
check('Communication rows use accepted accent tints', has(css,'.comm-type-icon.call') && has(css,'.comm-type-icon.email') && has(comm,'comm-type-icon ${item.type}') && has(messages,"messages-list-icon ${isWa ? 'wa' : 'sms'}"));
check('Icons stand alone without tile backgrounds', not(css,'.comm-type-icon.sms { background') && not(css,'.messages-list-icon.sms { background') && not(css,'.detail-activity-icon.teal { background') && not(css,'.comm-mini-actions a {\n  width: 27px;\n  height: 27px;\n  border: 0;\n  background: var(--bg-panel);'));
check('Call actions hover teal like the reference', has(css,'.detail-action-call:hover') && has(detail,'detail-action-call'));
check('Search fields use the dashboard focus ring', has(css,'.comm-search:focus-within') && has(css,'0 0 0 3px var(--accent-blue-light)'));
check('Neon purple and neon green are absent', !/#25C47A|#6B4EBC/i.test(css+app+nav+leads+detail+comm));
check('Authoritative CSS has no !important', !css.includes('!important'));
check('Detail cards use stat-box padding and border', has(css,'.detail-card {') && has(css,'padding: 13px 16px;') && has(css,'border: 1px solid var(--border);'));
check('Panel divider spacing is exactly 12px', has(app,'const DIVIDER_WIDTH = 12;') && has(css,'min-width: 12px;'));
check('Leads default width is 400px', has(app,'const DEFAULT_LEADS_WIDTH = 400;'));
check('Communications default width is 320px', has(app,'const DEFAULT_COMMS_WIDTH = 320;'));
check('Middle panel minimum width is protected', has(app,'const MIN_DETAIL_WIDTH = 340;'));
check('Both panel widths are saved', has(app,'saveWidth(PANEL_KEYS.leads, leadsWidth)') && has(app,'saveWidth(PANEL_KEYS.comms, commsWidth)'));
check('Both panel dividers are draggable', (app.match(/onPointerDown=/g)||[]).length===2);
check('Double-click reset exists on both dividers', (app.match(/onDoubleClick=\{resetPanels\}/g)||[]).length===2);
check('Settings can reset panel widths', has(settings,'onResetPanels'));
check('Topbar is the default navigation', has(store,"navMode: 'topbar'"));
check('Three-dot navigation cycles all 3 modes', has(app,"navMode === 'topbar' ? 'sidebar-slim' : navMode === 'sidebar-slim' ? 'sidebar-wide' : 'topbar'"));
check('Topbar and sidebars share one color setting', has(nav,'style={{ backgroundColor: navColor }}') && (nav.match(/backgroundColor: navColor/g)||[]).length===2);
check('Navigation includes Leads', has(nav,"label: 'Leads'"));
check('Navigation includes Messages', has(nav,"label: 'Messages'"));
check('Navigation includes Email', has(nav,"label: 'Email'"));
check('Navigation includes Scanner', has(nav,"label: 'Scanner'"));
check('Navigation includes Command', has(nav,"label: 'Command'"));
check('Font size uses plus/minus controls', has(settings,'<Minus size={16}/>') && has(settings,'<Plus size={16}/>'));
check('Font changes in 0.5px steps', has(settings,'changeFont(-0.5)') && has(settings,'changeFont(0.5)'));
check('Canvas colors are configurable', has(settings,'CANVAS_COLORS') && has(store,"canvasColor: '#F2F4F8'"));
check('Navigation colors are configurable', has(settings,'NAV_COLORS') && has(store,'sidebarColor'));
check('Settings persist locally', has(store,'localStorage.setItem(SETTINGS_KEY'));
check('Legacy settings migrate forward', has(store,"'forge-crm-ui-settings-v15'") && has(store,"'forge-crm-ui-settings-v14'"));
check('Default communications tab is configurable', has(settings,'Default Communications Tab') && has(store,'defaultCommsTab'));
check('Communications All tab exists', has(comm,"['all','messages','calls','contacts','email']") && has(comm,"tab.charAt(0).toUpperCase()+tab.slice(1)"));
check('Communications Messages tab exists', has(comm,"['all','messages','calls','contacts','email']") && has(comm,"activeTab === 'messages'"));
check('Communications Calls tab exists', has(comm,"['all','messages','calls','contacts','email']") && has(comm,"activeTab === 'calls'"));
check('Communications Contacts tab exists', has(comm,"['all','messages','calls','contacts','email']") && has(comm,"activeTab === 'contacts'"));
check('Communications Email tab exists', has(comm,"['all','messages','calls','contacts','email']") && has(comm,"activeTab === 'email'"));
check('All communications rows are clickable', has(comm,'onClick={() => openAllItem(item)}'));
check('Message conversation rows are clickable', has(comm,'onClick={() => openMessageThread(item,type)}'));
check('Call rows are clickable', has(comm,'setOpenCall(row)'));
check('Contact rows are clickable', has(comm,'setOpenContactId(item.id)'));
check('Email rows are clickable', has(comm,'openEmailComposer(row.lead,row.key,false)'));
check('Message conversations are sorted newest first', has(comm,'newestByTime') && has(messages,'ageMinutes'));
check('Messages page opens selected thread', has(messages,'setOpenedLeadId(item.id)'));
check('Contacts have a search field', has(comm,'placeholder="Search contacts"'));
check('Contacts are grouped alphabetically', has(comm,'groupedContacts'));
check('Contact call icon is available', has(comm,'title="Call"'));
check('Contact SMS icon is available', has(comm,'title="SMS"'));
check('Contact WhatsApp icon is available', has(comm,'title="WhatsApp"'));
check('Contact email icon is available', has(comm,'title="Email"'));
check('Message composer is inline', has(comm,'className="comm-composer"'));
check('Message Send uses paper-plane icon', has(comm,'<Send size={15}/>'));
check('Email compose/reply is inline', has(comm,'className="comm-email-compose"'));
check('Email Subject is inline', has(comm,'className="comm-email-subject"') && has(comm,'placeholder="Subject"'));
check('Opened email has Reply action', has(comm,'title="Reply"'));
check('No video icon exists in communications', not(comm,'Video'));
check('No info-circle control exists in communications', not(comm,'Info'));
check('Internal dialer code is absent', !/dialer|dtmf|keypad/i.test(app+nav+comm+css));
check('Call action never navigates the CRM to tel:', not(app,'window.location.href') && not(app,'tel:'));
check('Call action supports ForgeTelephonyAdapter', has(app,'ForgeTelephonyAdapter'));
check('Call action supports Electron/mobile event handoff', has(app,"new CustomEvent('forge:call-request'"));
check('Unhandled call request shows a notice', has(app,'Connect a phone or calling provider to place calls.'));
check('Lead list has no avatar/initial circle', not(leads,'avatar') && not(leads,'initial') && not(leads,'lead-avatar'));
check('Account initials are 15px and blue', has(css,'.forge-avatar {\n  width: 15px;\n  height: 15px;') && has(css,'.forge-avatar {') && has(css,'background: var(--accent-blue);'));
check('Lead header uses dashboard title and count pill', has(leads,'forge-leads-title-row') && has(leads,'panel-count'));
check('Lead company text uses dashboard name size', has(css,'.forge-lead-copy strong {\n  font-size: calc(12.5px + var(--font-offset));'));
check('Lead owner text uses dashboard muted size', has(css,'.forge-lead-copy span {\n  margin-top: 2px;') && has(css,'font-size: calc(10.5px + var(--font-offset));'));
check('Middle company title is large', has(css,'--text-title: 21px;') && has(css,'.detail-company-line h1'));
check('Owner and title sit directly under company title', has(detail,'detail-contact-name') && has(detail,'{lead.title}'));
check('Position shows as plain text without a pill box', not(detail,'detail-pill') && not(css,'.detail-pill') && has(detail,'{lead.pos} position'));
check('Approval is centered in header', has(css,'.detail-header-approval {\n  flex: 0 0 auto;\n  min-width: 132px;\n  text-align: center;'));
check('Financial strip uses real lead figures', has(detail,'fin-card') && has(detail,'lead.avg') && has(detail,'lead.ask') && has(detail,'lead.offer') && has(detail,'lead.bank.bal'));
check('Financial strip uses dashboard stat-box styling', has(css,'.fin-card {') && has(css,'.fin-card-bar.blue') && has(css,'.fin-card-bar.teal'));
check('Revenue and financial figures use Inter throughout', not(css,'--font-family-mono') && not(css,'className="mono"') && not(detail,'mono') && not(leads,'mono') && not(html,'JetBrains'));
check('Sales pitch is a card with the blue accent edge', has(css,'.detail-pitch {') && has(css,'border-left: 3px solid var(--accent-blue);'));
check('Activity rows use tinted reference icons', has(detail,'detail-activity-icon') && has(css,'.detail-activity-icon.teal') && has(css,'.detail-activity-icon.amber'));
check('Whole-dollar formatting is shared', has(format,'formatMoneyWhole') && has(leads,'formatMoneyWhole') && has(detail,'formatMoneyWhole'));
check('Employees field is removed', not(detail,"['Employees'"));
check('Contact groups align in an adaptive grid', has(css,'.detail-contact-groups') && has(css,'repeat(auto-fit, minmax(150px, 1fr))'));
check('Contact lines show values without per-number labels', not(detail,'detail-contact-label') && not(css,'.detail-contact-label'));
check('Card content uses larger heavier type', has(css,'.detail-contact-value') && has(css,'font-size: calc(12.5px + var(--font-offset));\n  font-weight: 600;') && has(css,'font-size: calc(11px + var(--font-offset));\n  font-weight: 600;') && has(css,'.detail-bank-rows strong'));
check('Card pairs stack on narrow panels', has(css,'.detail-pair {') && has(css,'repeat(auto-fit, minmax(280px, 1fr))'));
check('Mobile has call/SMS/WhatsApp actions', has(detail,'onMessage={() => onOpenMessages(item.n)} whatsapp'));
check('Landline has call action only', has(detail,'detail-landline-group'));
check('Statements section exists', has(detail,'Statements'));
check('Bank Account section exists', has(detail,'Bank Account'));
check('Sales Pitch section exists', has(detail,'Sales Pitch'));
check('Latest Activity shows two actions', has(detail,'lead.activity.slice(0,2)'));
check('Statement overlay exists', has(viewer,'role="dialog"'));
check('Statement viewer has newer navigation', has(viewer,'View newer statement'));
check('Statement viewer has older navigation', has(viewer,'View older statement'));
check('MTD statement is supported', has(detail,'lead.mtd') && has(statement,'index === -1'));
check('Original CRM lead records are preserved', has(data,'Northstar Catering Co.') && has(data,'Harborline Logistics') && has(data,'Brightwell Dental Group') && has(data,'Red Oak Auto Body') && has(data,'Lumen & Co. Interiors'));
check('Dashboard mock pipeline leads are absent', not(data,'Apex Dynamics') && not(data,'Sandra Reeves') && not(data,'NorthVector'));
check('Panel scrollbars are hidden until hover', has(css,'scrollbar-color: transparent transparent') && has(css,':hover::-webkit-scrollbar-thumb'));
check('Scrollbar width is skinny', has(css,'width: 5px;') && has(css,'height: 5px;'));
check('No form tags exist that can accidentally submit/reload', !/<form\b/i.test(app+nav+comm+detail+leads+messages+settings));
check('All explicit action buttons use type=button', (app+nav+comm+detail+leads+messages+settings).includes('type="button"'));
console.log(results.join('\n'));
console.log(`TOTAL ${passed}/${passed} PASS`);
